var fullName = 'Youssef Najjarine';
var isCool = false;
var totalPets = 1;
var unknown = null;
var never = ' ';
console.log(fullName);
console.log(isCool);
console.log(totalPets);
console.log(unknown);
console.log(never);
console.log(typeof 'Youssef Najjarine');
console.log(typeof false);
console.log(typeof 1);
console.log(typeof unknown);
console.log(typeof never);
